import React from 'react';
import { Branch, BranchKey, Skill } from '../types/skills';
import { Crosshair, Plus, Check, Zap, X } from 'lucide-react';
import { sounds } from '../utils/audio';

interface GrapevineNearRadarProps { focalSkill:Skill|null; allSkills:Skill[]; branches:Record<BranchKey,Branch>; basket:Skill[]; onSelectSkill:(skill:Skill)=>void; onAddToBasket:(skill:Skill)=>void; onClose:()=>void; }
export const GrapevineNearRadar:React.FC<GrapevineNearRadarProps>=({focalSkill,allSkills,branches,basket,onSelectSkill,onAddToBasket,onClose})=>{
 if(!focalSkill)return null;
 const focalBranch=branches[focalSkill.branchKey];
 const nearbySkills=allSkills.filter(s=>s.id!==focalSkill.id).map(s=>{let dAngle=Math.abs(s.angleDeg-focalSkill.angleDeg);if(dAngle>180)dAngle=360-dAngle;const normAngleDist=dAngle/180,dRadius=Math.abs(s.radius-focalSkill.radius),dHeight=Math.abs(s.heightY-focalSkill.heightY)/1.6,spatialDist=Math.sqrt(normAngleDist**2+dRadius**2+dHeight**2),isDirectCompatible=focalSkill.compatibleNeighbors.includes(s.id),isSameBranch=focalSkill.branchKey===s.branchKey,proximityScore=Math.max(0,Math.min(100,Math.round((1-spatialDist*.6)*100)+(isDirectCompatible?25:0)+(isSameBranch?15:0)));return{skill:s,branch:branches[s.branchKey],proximityScore,isDirectCompatible}}).sort((a,b)=>b.proximityScore-a.proximityScore).slice(0,6);
 return <div className="absolute top-20 right-4 w-88 max-w-[calc(100vw-32px)] bg-[#060e13]/95 backdrop-blur-md border border-[#39FF14]/40 rounded-2xl p-4 shadow-2xl z-30 transition-all">
  <div className="flex items-center justify-between pb-3 border-b border-white/10"><div className="flex items-center gap-2"><div className="w-6 h-6 rounded-full bg-[#39FF14]/15 border border-[#39FF14] flex items-center justify-center text-[#39FF14]"><Crosshair className="w-3.5 h-3.5 animate-pulse"/></div><div><h3 className="text-xs font-bold uppercase tracking-wider text-[#39FF14]">Grapevine Near Radar</h3><p className="text-[10px] text-zinc-400">Proximity & Pipeline Affinity</p></div></div><button onClick={onClose} className="text-zinc-400 hover:text-white p-1 rounded-lg hover:bg-white/5 transition-colors"><X className="w-4 h-4"/></button></div>
  <div className="my-3 p-2.5 rounded-xl bg-white/[0.03] border border-white/10 flex items-center justify-between"><div className="flex items-center gap-2.5 overflow-hidden"><div className="w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold shrink-0 border" style={{backgroundColor:`${focalBranch.color}20`,borderColor:focalBranch.color,color:focalBranch.color}}>{focalBranch.icon}</div><div className="truncate"><div className="text-xs font-bold text-white truncate">{focalSkill.name}</div><div className="text-[10px] text-zinc-400 flex items-center gap-1.5 font-mono"><span>{focalSkill.registryState.replace('CANONICAL_','')}</span><span>·</span><span style={{color:focalBranch.color}}>{focalBranch.title}</span></div></div></div><span className="text-[9px] font-mono font-bold px-2 py-0.5 rounded bg-[#39FF14]/20 text-[#39FF14] border border-[#39FF14]/40">ORIGIN</span></div>
  <div className="text-[10px] font-mono font-bold tracking-wider text-zinc-500 uppercase mb-2">Nearest Bio-Tendril Neighbors</div>
  <div className="space-y-2 max-h-64 overflow-y-auto pr-1">{nearbySkills.map(({skill,branch,proximityScore,isDirectCompatible})=>{const isHarvested=basket.some(b=>b.id===skill.id);return <div key={skill.id} onClick={()=>{sounds.playClick();onSelectSkill(skill)}} className="p-2.5 rounded-xl bg-black/40 hover:bg-white/[0.06] border border-white/5 hover:border-[#39FF14]/50 cursor-pointer transition-all group flex items-center justify-between gap-2"><div className="flex items-center gap-2.5 overflow-hidden"><div className="w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold shrink-0 border" style={{backgroundColor:`${branch.color}15`,borderColor:branch.color,color:branch.color}}>{branch.icon}</div><div className="truncate"><div className="text-[11px] font-bold text-white group-hover:text-[#39FF14] transition-colors truncate">{skill.name}</div><div className="text-[9.5px] text-zinc-400 flex items-center gap-1.5 font-mono"><span className="text-[#39FF14]">{skill.registryState.replace('CANONICAL_','')}</span><span>·</span><span>{proximityScore}% Near</span>{isDirectCompatible&&<><span>·</span><span className="text-[#ff007f] font-semibold">Chain</span></>}</div></div></div><button type="button" title={isHarvested?'Already in Harvest Basket':'Harvest to Pipeline Basket'} onClick={e=>{e.stopPropagation();sounds.playPop();onAddToBasket(skill)}} className={`p-1.5 rounded-lg border text-xs transition-all ${isHarvested?'bg-[#39FF14]/20 border-[#39FF14] text-[#39FF14]':'bg-white/5 border-white/10 text-zinc-300 hover:border-[#39FF14] hover:text-[#39FF14]'}`}>{isHarvested?<Check className="w-3.5 h-3.5"/>:<Plus className="w-3.5 h-3.5"/>}</button></div>})}</div>
  <div className="mt-3 pt-2.5 border-t border-white/10 flex items-center justify-between text-[10px] font-mono text-zinc-400"><span className="flex items-center gap-1"><Zap className="w-3 h-3 text-[#39FF14]"/>Canonical registry adjacency</span><span className="text-[#38edf8]">Execution requires authorized runtime</span></div>
 </div>;
};