import React from 'react';
import { Branch, BranchKey, Skill } from '../types/skills';
import { Play, RotateCcw, Download, Sparkles, X, ShieldCheck } from 'lucide-react';
import { sounds } from '../utils/audio';

interface HarvestBasketProps { basket: Skill[]; branches: Record<BranchKey, Branch>; onRemoveSkill:(skillId:string)=>void; onClearBasket:()=>void; onInspectSkill:(skill:Skill)=>void; onExecutePipeline:()=>void; onExportPipeline:()=>void; onSuggestNear:()=>void; }

export const HarvestBasket: React.FC<HarvestBasketProps> = ({ basket, branches, onRemoveSkill, onClearBasket, onInspectSkill, onExecutePipeline, onExportPipeline, onSuggestNear }) => {
  const maxSlots=5;
  return <div className="absolute bottom-4 left-4 right-4 md:left-8 md:right-8 bg-[#060e13]/95 backdrop-blur-xl border border-[#39FF14]/50 rounded-2xl p-3 md:p-4 shadow-[0_12px_45px_rgba(0,0,0,0.85)] z-20 transition-all">
    <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
      <div className="flex items-center gap-3"><div className="flex items-center gap-2"><div className="w-2.5 h-2.5 rounded-full bg-[#39FF14] animate-ping"/><h2 className="text-xs md:text-sm font-black tracking-widest text-[#39FF14] uppercase">Agent Harvest Basket</h2></div><span className="text-[11px] font-mono text-zinc-400">{basket.length}/{maxSlots} canonical skills selected</span>{basket.length>0&&<div className="hidden sm:flex items-center gap-2 text-[10px] font-mono text-zinc-400"><span>·</span><span className="text-[#38edf8] font-bold flex items-center gap-1"><ShieldCheck className="w-3 h-3"/>Selection only — execution still requires Runtime Fabric authority</span></div>}</div>
      <div className="flex items-center gap-2">{basket.length<maxSlots&&<button onClick={()=>{sounds.playChime();onSuggestNear()}} title="Suggest a nearby canonical skill" className="h-8 px-2.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 hover:border-[#39FF14] text-[11px] font-mono font-medium text-zinc-300 hover:text-[#39FF14] flex items-center gap-1.5 transition-all"><Sparkles className="w-3.5 h-3.5 text-[#39FF14]"/><span className="hidden sm:inline">Near Suggest</span></button>}{basket.length>0&&<><button onClick={()=>{sounds.playClick();onExportPipeline()}} className="h-8 px-2.5 rounded-xl bg-white/5 hover:bg-white/10 border border-white/10 hover:border-[#38edf8] text-[11px] font-mono font-medium text-zinc-300 hover:text-[#38edf8] flex items-center gap-1.5 transition-all"><Download className="w-3.5 h-3.5"/><span className="hidden sm:inline">Export Manifest</span></button><button onClick={()=>{sounds.playClick();onClearBasket()}} className="h-8 px-2 rounded-xl text-zinc-400 hover:text-white hover:bg-white/5 transition-colors"><RotateCcw className="w-3.5 h-3.5"/></button></>}<button onClick={()=>{if(!basket.length)return;sounds.playChime();onExecutePipeline()}} disabled={!basket.length} className={`h-8 px-3.5 rounded-xl font-black text-xs tracking-wider flex items-center gap-1.5 uppercase transition-all shadow-lg ${basket.length?'bg-[#39FF14] text-black hover:bg-[#32e012]':'bg-zinc-800 text-zinc-500 cursor-not-allowed border border-zinc-700'}`}><Play className="w-3.5 h-3.5 fill-current"/><span>Pipeline Gate</span></button></div>
    </div>
    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-2">{Array.from({length:maxSlots}).map((_,index)=>{const skill=basket[index];if(skill){const branch=branches[skill.branchKey];return <div key={skill.id} onClick={()=>{sounds.playClick();onInspectSkill(skill)}} style={{borderColor:`${branch.color}80`}} className="group relative h-14 rounded-xl bg-[#09151c]/90 border p-2 flex flex-col justify-between cursor-pointer hover:bg-white/[0.07] transition-all"><div className="flex items-center justify-between gap-1"><div className="flex items-center gap-1.5 truncate"><span className="text-xs shrink-0" style={{color:branch.color}}>{branch.icon}</span><span className="text-[11px] font-bold text-white truncate group-hover:text-[#39FF14]">{skill.name}</span></div><button onClick={(e)=>{e.stopPropagation();sounds.playPop();onRemoveSkill(skill.id)}} className="w-4 h-4 rounded-full bg-black/60 hover:bg-red-500/80 text-zinc-400 hover:text-white flex items-center justify-center"><X className="w-2.5 h-2.5"/></button></div><div className="flex items-center justify-between text-[9px] font-mono text-zinc-400"><span style={{color:branch.color}}>SLOT {index+1}</span><span className="text-[#39FF14]">{skill.registryState.replace('CANONICAL_','')}</span></div></div>}return <div key={index} className="h-14 rounded-xl border border-dashed border-white/10 bg-black/30 flex flex-col items-center justify-center text-zinc-600 font-mono text-[10px]"><span>EMPTY SLOT {index+1}</span><span className="text-[8px] text-zinc-700">Click grape to harvest</span></div>})}</div>
  </div>;
};
