import React, { useMemo, useState } from 'react';
import { Skill, Branch, BranchKey, GrapevineRegistry } from '../types/skills';
import { X, Copy, Check, Terminal, ShieldAlert, CircleDot } from 'lucide-react';
import { sounds } from '../utils/audio';

interface PipelineRunnerModalProps { basket: Skill[]; branches: Record<BranchKey, Branch>; registry:GrapevineRegistry|null; onClose:()=>void; }
export const PipelineRunnerModal:React.FC<PipelineRunnerModalProps>=({basket,registry,onClose})=>{
 const[copied,setCopied]=useState(false);
 const manifest=useMemo(()=>JSON.stringify({schemaVersion:'leeway.grapevine.selection.v1',generatedAt:new Date().toISOString(),sourceCommit:registry?.commit||null,execution:'NOT_TRIGGERED_FROM_GITHUB_PAGES',skills:basket.map((s,i)=>({sequence:i+1,id:s.id,path:s.githubPath,registryState:s.registryState,qualificationState:s.qualificationState,executionState:s.executionState}))},null,2),[basket,registry]);
 const copy=()=>{navigator.clipboard.writeText(manifest);setCopied(true);sounds.playClick();setTimeout(()=>setCopied(false),1800)};
 return <div onClick={onClose} className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md"><div onClick={e=>e.stopPropagation()} className="w-full max-w-2xl bg-[#030708] border border-[#39FF14] rounded-2xl p-5 md:p-6 shadow-[0_20px_80px_rgba(0,0,0,0.95)] flex flex-col max-h-[90vh]">
  <div className="flex items-center justify-between pb-3 border-b border-white/10 mb-4"><div className="flex items-center gap-2.5"><div className="w-8 h-8 rounded-full bg-[#39FF14]/15 border border-[#39FF14] flex items-center justify-center text-[#39FF14]"><Terminal className="w-4 h-4"/></div><div><h3 className="text-sm font-black text-[#39FF14] tracking-wider uppercase">Pipeline Authority Gate</h3><p className="text-[11px] text-zinc-400 font-mono">{basket.length} harvested canonical skills · no simulated execution</p></div></div><button onClick={onClose} className="text-zinc-400 hover:text-white"><X className="w-5 h-5"/></button></div>
  <div className="grid grid-cols-3 gap-2.5 mb-4"><div className="p-2.5 rounded-xl bg-white/[0.02] border border-white/10 text-center"><div className="text-[9px] text-zinc-400 uppercase">Public Pages</div><div className="text-sm font-black text-amber-300 font-mono">READ / SELECT</div></div><div className="p-2.5 rounded-xl bg-white/[0.02] border border-white/10 text-center"><div className="text-[9px] text-zinc-400 uppercase">MCP Inventory</div><div className="text-sm font-black text-[#38edf8] font-mono">{registry?.counts.mcpProtocolListedTools??'—'}</div></div><div className="p-2.5 rounded-xl bg-white/[0.02] border border-white/10 text-center"><div className="text-[9px] text-zinc-400 uppercase">Execution</div><div className="text-sm font-black text-red-300 font-mono">NOT TRIGGERED</div></div></div>
  <div className="mb-4 rounded-xl border border-amber-500/30 bg-amber-950/10 p-3 text-xs text-zinc-300 leading-relaxed flex gap-2"><ShieldAlert className="w-4 h-4 text-amber-300 shrink-0"/>GitHub Pages can select and export canonical skills, but it cannot truthfully claim local MCP, Desktop Commander, Device Bridge, Formula, or Veritas execution.</div>
  <div className="flex-1 bg-[#010406] border border-white/15 rounded-xl p-3.5 font-mono text-xs overflow-y-auto space-y-2 min-h-[230px] max-h-[360px]">{basket.map((s,i)=><div key={s.id} className="border-l-2 border-[#39FF14] pl-2.5 py-1"><div className="flex items-center gap-2 text-[10px] text-zinc-500"><CircleDot className="w-3 h-3 text-[#39FF14]"/><span>STEP {i+1}</span><span className="text-white font-bold">{s.name}</span></div><div className="text-[#38edf8] text-[10px] mt-1 break-all">{s.githubPath}</div><div className="text-zinc-400 text-[10px] mt-1">registry={s.registryState} · qualification={s.qualificationState} · execution={s.executionState}</div></div>)}</div>
  <div className="flex items-center justify-between pt-4 mt-2 border-t border-white/10"><span className="text-[10px] text-zinc-500 font-mono">Selection manifest only — not an execution receipt.</span><button onClick={copy} className="px-4 py-2 rounded-xl bg-[#39FF14] text-black font-black text-xs font-mono uppercase flex items-center gap-1.5">{copied?<Check className="w-3.5 h-3.5"/>:<Copy className="w-3.5 h-3.5"/>}{copied?'Copied':'Copy Manifest'}</button></div>
 </div></div>
};
